services:
  - type: web
    name: psychnow-api
    runtime: python
    region: ohio
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python -c 'import time; time.sleep(10)' && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: psychnow-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: OPENAI_MAX_TOKENS
        value: 2000
      - key: ALLOWED_ORIGINS
        sync: false
      - key: PROVIDER_INVITE_CODE
        value: PSYCHNOW-PROVIDER-2024
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        value: gb.tolani@gmail.com
      - key: FROM_EMAIL
        value: noreply@psychnow.com

databases:
  - name: psychnow-db
    databaseName: psychnow
    user: psychnow
    plan: free

