"""add_pause_resume_functionality

Revision ID: 2ec613c9177f
Revises: 67c26704418e
Create Date: 2025-10-02 12:33:47.953650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec613c9177f'
down_revision = '67c26704418e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_sessions') as batch_op:
        batch_op.add_column(sa.Column('paused_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resume_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('completed_screeners', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('current_screener', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('screener_progress', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_sessions') as batch_op:
        batch_op.drop_column('screener_progress')
        batch_op.drop_column('current_screener')
        batch_op.drop_column('completed_screeners')
        batch_op.drop_column('resume_token')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('paused_at')
    # ### end Alembic commands ###

